# Generated by Django 5.2.4 on 2025-07-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpaformdata',
            name='document',
        ),
    ]
